package com.example.psk1lab.mybatis.model;

public class Artist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.ID
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.ARTIST_NAME
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    private String artistName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.ID
     *
     * @return the value of PUBLIC.ARTIST.ID
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.ID
     *
     * @param id the value for PUBLIC.ARTIST.ID
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.ARTIST_NAME
     *
     * @return the value of PUBLIC.ARTIST.ARTIST_NAME
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public String getArtistName() {
        return artistName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.ARTIST_NAME
     *
     * @param artistName the value for PUBLIC.ARTIST.ARTIST_NAME
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public void setArtistName(String artistName) {
        this.artistName = artistName;
    }
}