package com.example.psk1lab.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;


@Getter @Setter
public class Genre {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GENRE.ID
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GENRE.GENRE_NAME
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    private String genreName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GENRE.ID
     *
     * @return the value of PUBLIC.GENRE.ID
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GENRE.ID
     *
     * @param id the value for PUBLIC.GENRE.ID
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GENRE.GENRE_NAME
     *
     * @return the value of PUBLIC.GENRE.GENRE_NAME
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public String getGenreName() {
        return genreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GENRE.GENRE_NAME
     *
     * @param genreName the value for PUBLIC.GENRE.GENRE_NAME
     *
     * @mbg.generated Wed May 11 10:29:50 EEST 2022
     */
    public void setGenreName(String genreName) {
        this.genreName = genreName;
    }

    private List<Song> songs;
}