package com.example.psk1lab.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter @Setter
public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.AUTHOR_ID
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    private Long authorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.TITLE
     *
     * @return the value of PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.TITLE
     *
     * @param title the value for PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.AUTHOR_ID
     *
     * @return the value of PUBLIC.SONG.AUTHOR_ID
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.AUTHOR_ID
     *
     * @param authorId the value for PUBLIC.SONG.AUTHOR_ID
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    private List<Genre> genres;
}