package com.example.psk1lab.mybatis.dao;

import com.example.psk1lab.mybatis.model.Album;
import com.example.psk1lab.mybatis.model.Artist;
import com.example.psk1lab.mybatis.model.Song;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface ArtistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    int insert(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    Artist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    List<Artist> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARTIST
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    int updateByPrimaryKey(Artist record);

    List<Album> selectAlbumsForArtist(Integer id);
    List<Song> selectSongsForArtist(Integer id);
}