package com.example.psk1lab.mybatis.dao;

import com.example.psk1lab.mybatis.model.Song;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    Song selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    List<Song> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue May 17 13:12:24 EEST 2022
     */
    int updateByPrimaryKey(Song record);

    Song findByName(String name);

    int getResultCountBySongTitle(String name);
}