package com.example.psk1lab.mybatis.dao;

import com.example.psk1lab.mybatis.model.Artist;
import com.example.psk1lab.mybatis.model.Song;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    int deleteByPrimaryKey(Integer songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    Song selectByPrimaryKey(Integer songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    List<Song> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Mon May 02 21:27:07 EEST 2022
     */
    int updateByPrimaryKey(Song record);

    List<Artist> selectArtistsForSong(Integer id);
}